### ISSUE TITLE
How to deal with lint ?

### ISSUE THREAD

**Issue by Ridermansb** [zapplebee/perenv.macro#1]
First.. congrats. This is a awesome library!

Just an question, how did you deal with lint errors ..like 

```
import { loadPerEnv } from "./perEnv.macro";
loadPerEnv({path: './feature.js', identifier: 'feature'}, 'NODE_ENV', "dev");


function () {
    feature.sendEmail();     <--- HERE `feature` lint appear as not defined!
}
```

**Comment by zapplebee** [comment]
I am considering an alternative API for this.

Something that would transform an assignment into an import.

Along the lines of this


```javascript
const feature = loadByAssignment('./feature.js', 'NODE_ENV', 'dev')

⬇⬇⬇⬇

import * as feature from './feature.js'

```

My major hang up with this would be what happens when the environment does no assignments (i.e. NODE_ENV is not set to dev)

Another issue here is that multiple assignments will also be discouraged by the linter.

```javascript
const feature = loadByAssignment('./feature.js', 'NODE_ENV', 'production')
const feature = loadByAssignment('./new_feature.js', 'NODE_ENV', 'dev')

```

I think first I would want to solidify a map API.

```javascript
loadPerEnvMap(
  {
    environments: { dev: "./new_feature.js", default: "./feature.js" },
    identifier: "feature",
  },
  "NODE_ENV"
);

```

Looking for commentary before moving forward with the approach though.

**Comment by Ridermansb** [comment]
So.. if ` when the environment does no assignments` just do not do nothing...

```
const feature = loadByAssignment('./feature.js', 'NODE_ENV', 'dev')

⬇⬇⬇⬇


```


about `multiple assignments will also be discouraged by the linter.` that's true.  

Why not..

```
const feature = loadPerEnvMap(
  { environments: { dev: "./new_feature.js", production: "./feature.js" } },
  "NODE_ENV"
);
```

I think, `default` it's not necessary. You must guarantee that environment variable is set. Otherwise the `feature` will be disabled.

**Comment by zapplebee** [comment]
I am working on a feature mostly like the second example you have

```javascript

const feature = assignPerEnvMap(
  { dev: "./new_feature.js", production: "./feature.js" },
  "NODE_ENV"
);

⬇⬇⬇⬇

import * as feature from './feature.js'

```

I am unsure how I want to handle the case when no match is found. I think throwing a build-time error would be fine since this code should only ever be static.

I do want to handle a default case though, it may not be a required value. Still unsure.

**Comment by zapplebee** [comment]
@Ridermansb I've opened a pull request for your open issue. A review would be appreciated.
